spring:
  profiles: local

  datasource:
    data: classpath:bank.sql
    platform: h2
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop

server:
  tomcat:
    accesslog:
      pattern: common - %a %u %{yyyy-MM-dd HH:mm:ss}t "%r" %s %b
      enabled: true
    basedir: c:/housingfinance/log
  port: 9090

management:
  security:
    enabled: false

static:
  resource:
    location: file:///C:/housingfinance/


---
