INSERT INTO BANK VALUES ('주택도시기금', 'BNK093');
INSERT INTO BANK VALUES ('국민은행', 'BNK019');
INSERT INTO BANK VALUES ('우리은행', 'BNK020');
INSERT INTO BANK VALUES ('신한은행', 'BNK021');
INSERT INTO BANK VALUES ('한국시티은행','BNK027');
INSERT INTO BANK VALUES ('하나은행','BNK025');
INSERT INTO BANK VALUES ('농협은행/수협은행', 'BNK012');
INSERT INTO BANK VALUES ('외환은행','BNK005');
INSERT INTO BANK VALUES ('기타은행','BNK051');